//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainzBasemapMaker.Localization {
    using System;
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrainzBasemapMaker.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string App_Title => ResourceManager.GetString("App_Title", resourceCulture) ?? "Trainz Basemap Maker";
        public static string Common_OK => ResourceManager.GetString("Common_OK", resourceCulture) ?? "OK";
        public static string Common_Cancel => ResourceManager.GetString("Common_Cancel", resourceCulture) ?? "Cancel";
        public static string Common_Confirm => ResourceManager.GetString("Common_Confirm", resourceCulture) ?? "Confirm";
        public static string Common_Browse => ResourceManager.GetString("Common_Browse", resourceCulture) ?? "Browse...";
        public static string Common_Error => ResourceManager.GetString("Common_Error", resourceCulture) ?? "Error";
        public static string Common_CriticalError => ResourceManager.GetString("Common_CriticalError", resourceCulture) ?? "Critical Error";
        public static string Common_Warning => ResourceManager.GetString("Common_Warning", resourceCulture) ?? "Warning";
        public static string Common_Information => ResourceManager.GetString("Common_Information", resourceCulture) ?? "Information";
        public static string Common_Success => ResourceManager.GetString("Common_Success", resourceCulture) ?? "Success";
        public static string Common_InputError => ResourceManager.GetString("Common_InputError", resourceCulture) ?? "Input Error";
        public static string Common_OnlyDigitsTooltip => ResourceManager.GetString("Common_OnlyDigitsTooltip", resourceCulture) ?? "Only numbers are allowed here!";
        public static string Common_Ready => ResourceManager.GetString("Common_Ready", resourceCulture) ?? "Ready.";
        public static string Common_CoordSystem => ResourceManager.GetString("Common_CoordSystem", resourceCulture) ?? "Coordinate system";
        public static string Common_Epsg2180 => ResourceManager.GetString("Common_Epsg2180", resourceCulture) ?? "EPSG:2180 (Poland)";
        public static string Common_Epsg3857 => ResourceManager.GetString("Common_Epsg3857", resourceCulture) ?? "EPSG:3857 (World)";
        public static string Common_UnhandledAppError => ResourceManager.GetString("Common_UnhandledAppError", resourceCulture) ?? "An unexpected application error occurred:\n\n{0}\n\n{1}";
        public static string Common_UiError => ResourceManager.GetString("Common_UiError", resourceCulture) ?? "User interface error:\n\n{0}\n\n{1}";

        public static string Main_Menu_Tools => ResourceManager.GetString("Main_Menu_Tools", resourceCulture) ?? "&Tools";
        public static string Main_Menu_FindFreeKuid => ResourceManager.GetString("Main_Menu_FindFreeKuid", resourceCulture) ?? "Find Free &KUID Number";
        public static string Main_Menu_FindSmallestFreeBasemap => ResourceManager.GetString("Main_Menu_FindSmallestFreeBasemap", resourceCulture) ?? "Find Lowest Free &Basemap Number";
        public static string Main_Menu_RefreshFolderList => ResourceManager.GetString("Main_Menu_RefreshFolderList", resourceCulture) ?? "&Refresh Folder List";
        public static string Main_Menu_BatchProcessing => ResourceManager.GetString("Main_Menu_BatchProcessing", resourceCulture) ?? "Batch &Processing";
        public static string Main_Menu_Preferences => ResourceManager.GetString("Main_Menu_Preferences", resourceCulture) ?? "P&references";
        public static string Main_Menu_Help => ResourceManager.GetString("Main_Menu_Help", resourceCulture) ?? "&Help";
        public static string Main_Menu_GitHubWebsite => ResourceManager.GetString("Main_Menu_GitHubWebsite", resourceCulture) ?? "&Project Website - GitHub";
        public static string Main_Menu_About => ResourceManager.GetString("Main_Menu_About", resourceCulture) ?? "&About";
        public static string Main_Tab_Single => ResourceManager.GetString("Main_Tab_Single", resourceCulture) ?? "Single Basemap (2D)";
        public static string Main_Tab_Unified => ResourceManager.GetString("Main_Tab_Unified", resourceCulture) ?? "Area Download & Terrain (3D)";
        public static string Main_Status_NewVersionAvailable => ResourceManager.GetString("Main_Status_NewVersionAvailable", resourceCulture) ?? "A new version of the program has been released: {0}.";

        public static string Pref_Title => ResourceManager.GetString("Pref_Title", resourceCulture) ?? "Preferences";
        public static string Pref_Header => ResourceManager.GetString("Pref_Header", resourceCulture) ?? "Preferences:";
        public static string Pref_AutoCounter => ResourceManager.GetString("Pref_AutoCounter", resourceCulture) ?? "Automatically increment basemap number";
        public static string Pref_AutoKuid => ResourceManager.GetString("Pref_AutoKuid", resourceCulture) ?? "Automatically set KUID part 2";
        public static string Pref_KuidPerPart1 => ResourceManager.GetString("Pref_KuidPerPart1", resourceCulture) ?? "Find free KUID part 2 separately for each part 1";
        public static string Pref_DefaultKuidPart1 => ResourceManager.GetString("Pref_DefaultKuidPart1", resourceCulture) ?? "Default KUID part 1";
        public static string Pref_MinKuidPart2 => ResourceManager.GetString("Pref_MinKuidPart2", resourceCulture) ?? "Minimum value for KUID part 2";
        public static string Pref_DarkMode => ResourceManager.GetString("Pref_DarkMode", resourceCulture) ?? "Dark mode";
        public static string Pref_BasemapSize => ResourceManager.GetString("Pref_BasemapSize", resourceCulture) ?? "Basemap size (m)";
        public static string Pref_Generate3D => ResourceManager.GetString("Pref_Generate3D", resourceCulture) ?? "Generate 3D basemaps (requires Trainz Mesh Importer)";
        public static string Pref_TmiPath => ResourceManager.GetString("Pref_TmiPath", resourceCulture) ?? "Path to TrainzMeshImporter.exe:";
        public static string Pref_Language => ResourceManager.GetString("Pref_Language", resourceCulture) ?? "Language:";
        public static string Pref_Language_English => ResourceManager.GetString("Pref_Language_English", resourceCulture) ?? "English";
        public static string Pref_Language_Polish => ResourceManager.GetString("Pref_Language_Polish", resourceCulture) ?? "Polski";
        public static string Pref_TmiFilter => ResourceManager.GetString("Pref_TmiFilter", resourceCulture) ?? "TrainzMeshImporter.exe|TrainzMeshImporter.exe|All files (*.*)|*.*";

        public static string About_Title => ResourceManager.GetString("About_Title", resourceCulture) ?? "About";
        public static string About_Version => ResourceManager.GetString("About_Version", resourceCulture) ?? "Version:";
        public static string About_ReleaseDate => ResourceManager.GetString("About_ReleaseDate", resourceCulture) ?? "Release date:";
        public static string About_Author => ResourceManager.GetString("About_Author", resourceCulture) ?? "Author:";
        public static string About_License => ResourceManager.GetString("About_License", resourceCulture) ?? "License:";
        public static string About_GitHub => ResourceManager.GetString("About_GitHub", resourceCulture) ?? "Project Website - GitHub:";
        public static string About_Libraries => ResourceManager.GetString("About_Libraries", resourceCulture) ?? "This program uses the following libraries:\r\n- Microsoft.Web.WebView2 - license: Microsoft\r\n- Leaflet - license: BSD 2-Clause License\r\n- ProjNET - license: LGPL v2.1";
        public static string About_OpenUrlError => ResourceManager.GetString("About_OpenUrlError", resourceCulture) ?? "Error opening website:\n\n{0}";

        public static string MapPicker_Title => ResourceManager.GetString("MapPicker_Title", resourceCulture) ?? "Pick Location on Map";
        public static string MapPicker_GeoCoords => ResourceManager.GetString("MapPicker_GeoCoords", resourceCulture) ?? "Geographic coordinates:";
        public static string MapPicker_Lat => ResourceManager.GetString("MapPicker_Lat", resourceCulture) ?? "latitude (lat)";
        public static string MapPicker_Lon => ResourceManager.GetString("MapPicker_Lon", resourceCulture) ?? "longitude (lon)";
        public static string MapPicker_InvalidCoords => ResourceManager.GetString("MapPicker_InvalidCoords", resourceCulture) ?? "Coordinates have an invalid format!";

        public static string Batch_Title => ResourceManager.GetString("Batch_Title", resourceCulture) ?? "Batch Processing";
        public static string Batch_Header => ResourceManager.GetString("Batch_Header", resourceCulture) ?? "Batch processing:";
        public static string Batch_Group1 => ResourceManager.GetString("Batch_Group1", resourceCulture) ?? "1. Select folder to process";
        public static string Batch_YourFolders => ResourceManager.GetString("Batch_YourFolders", resourceCulture) ?? "Your folders:";
        public static string Batch_Group2 => ResourceManager.GetString("Batch_Group2", resourceCulture) ?? "2. Select coordinate system";
        public static string Batch_Group3 => ResourceManager.GetString("Batch_Group3", resourceCulture) ?? "3. Set target parameters";
        public static string Batch_MapType => ResourceManager.GetString("Batch_MapType", resourceCulture) ?? "Basemap type:";
        public static string Batch_MapYear => ResourceManager.GetString("Batch_MapYear", resourceCulture) ?? "Basemap\r\nyear:";
        public static string Batch_Resolution => ResourceManager.GetString("Batch_Resolution", resourceCulture) ?? "Basemap\r\nresolution [px]:";
        public static string Batch_BasemapDesignation => ResourceManager.GetString("Batch_BasemapDesignation", resourceCulture) ?? "Basemap name:";
        public static string Batch_DestFolder => ResourceManager.GetString("Batch_DestFolder", resourceCulture) ?? "Destination folder name:";
        public static string Batch_ButtonProcess => ResourceManager.GetString("Batch_ButtonProcess", resourceCulture) ?? "Batch Process";
        public static string Batch_Processed => ResourceManager.GetString("Batch_Processed", resourceCulture) ?? "Processed:";
        public static string Batch_ProgressFormat => ResourceManager.GetString("Batch_ProgressFormat", resourceCulture) ?? "Processed: {0} of {1}";
        public static string Batch_Err_SelectSource => ResourceManager.GetString("Batch_Err_SelectSource", resourceCulture) ?? "Select a source basemap group!";
        public static string Batch_Err_EnterDestFolder => ResourceManager.GetString("Batch_Err_EnterDestFolder", resourceCulture) ?? "Enter the destination folder name!";
        public static string Batch_Err_EnterDesignation => ResourceManager.GetString("Batch_Err_EnterDesignation", resourceCulture) ?? "Enter the basemap designation!";
        public static string Batch_Err_DestSameAsSource => ResourceManager.GetString("Batch_Err_DestSameAsSource", resourceCulture) ?? "The destination folder name must be different from the source folder name!";
        public static string Batch_Err_TileAlreadyExists => ResourceManager.GetString("Batch_Err_TileAlreadyExists", resourceCulture) ?? "Tile {0}: Basemap with coordinates {1}, {2} already exists.";
        public static string Batch_Err_InvalidFolderFormat => ResourceManager.GetString("Batch_Err_InvalidFolderFormat", resourceCulture) ?? "Tile {0}: Invalid basemap folder name format.";
        public static string Batch_Confirm_Overwrite => ResourceManager.GetString("Batch_Confirm_Overwrite", resourceCulture) ?? "The folder \"{0}\" already exists. Continuing will overwrite existing files with the same names.\n\nDo you want to continue?";
        public static string Batch_Success => ResourceManager.GetString("Batch_Success", resourceCulture) ?? "Batch processing completed successfully!\n\nSuccessfully created basemaps: {0} of {1}.";
        public static string Batch_Warnings => ResourceManager.GetString("Batch_Warnings", resourceCulture) ?? "Batch processing finished with warnings.\n\nCreated basemaps: {0} of {1}.\nFailures ({2}):\n{3}";
        public static string Batch_Failed => ResourceManager.GetString("Batch_Failed", resourceCulture) ?? "Batch processing failed for all basemaps (0 of {0}).\n\nError details:\n{1}";
        public static string Batch_ProcessingError => ResourceManager.GetString("Batch_ProcessingError", resourceCulture) ?? "Processing error";
        public static string Batch_CriticalError => ResourceManager.GetString("Batch_CriticalError", resourceCulture) ?? "Critical error: {0}";
        public static string Batch_Status_Downloading => ResourceManager.GetString("Batch_Status_Downloading", resourceCulture) ?? "Processing {0}/{1}...";
        public static string Batch_Status_Done => ResourceManager.GetString("Batch_Status_Done", resourceCulture) ?? "Batch processing completed.";
        public static string Batch_Status_Cancelled => ResourceManager.GetString("Batch_Status_Cancelled", resourceCulture) ?? "Batch processing cancelled.";

        public static string Single_GroupGeoCoords => ResourceManager.GetString("Single_GroupGeoCoords", resourceCulture) ?? "1. Geographic coordinates (DD)";
        public static string Single_Lat => ResourceManager.GetString("Single_Lat", resourceCulture) ?? "latitude (lat)";
        public static string Single_Lon => ResourceManager.GetString("Single_Lon", resourceCulture) ?? "longitude (lon)";
        public static string Single_PickOnMap => ResourceManager.GetString("Single_PickOnMap", resourceCulture) ?? "Pick on map";
        public static string Single_GroupTargetCoords => ResourceManager.GetString("Single_GroupTargetCoords", resourceCulture) ?? "2. Target coordinate format";
        public static string Single_CoordsLabelFormat => ResourceManager.GetString("Single_CoordsLabelFormat", resourceCulture) ?? "Coordinates {0}";
        public static string Single_ConvertCoordsFormat => ResourceManager.GetString("Single_ConvertCoordsFormat", resourceCulture) ?? "Convert to {0}";
        public static string Single_GroupConfigurator => ResourceManager.GetString("Single_GroupConfigurator", resourceCulture) ?? "3. Configuration of downloaded and generated basemaps";
        public static string Single_CreateTrainzFiles => ResourceManager.GetString("Single_CreateTrainzFiles", resourceCulture) ?? "Create Trainz folders and files";
        public static string Single_Gen3DBasemaps => ResourceManager.GetString("Single_Gen3DBasemaps", resourceCulture) ?? "Generate\r\n3D basemaps";
        public static string Single_DestFolder => ResourceManager.GetString("Single_DestFolder", resourceCulture) ?? "Destination folder name:";
        public static string Single_YourFolders => ResourceManager.GetString("Single_YourFolders", resourceCulture) ?? "Your folders:";
        public static string Single_BasemapNum => ResourceManager.GetString("Single_BasemapNum", resourceCulture) ?? "Basemap #:";
        public static string Single_KuidPart1 => ResourceManager.GetString("Single_KuidPart1", resourceCulture) ?? "KUID designation:";
        public static string Single_BasemapDesignation => ResourceManager.GetString("Single_BasemapDesignation", resourceCulture) ?? "Basemap name:";
        public static string Single_GroupBasemapParams => ResourceManager.GetString("Single_GroupBasemapParams", resourceCulture) ?? "4. Satellite basemap parameters";
        public static string Single_MapType => ResourceManager.GetString("Single_MapType", resourceCulture) ?? "Basemap type:";
        public static string Single_MapYear => ResourceManager.GetString("Single_MapYear", resourceCulture) ?? "Basemap\r\nyear:";
        public static string Single_Resolution => ResourceManager.GetString("Single_Resolution", resourceCulture) ?? "Resolution [px]:";
        public static string Single_BtnConfigAndDownload => ResourceManager.GetString("Single_BtnConfigAndDownload", resourceCulture) ?? "Configure and download";
        public static string Single_BtnDownload => ResourceManager.GetString("Single_BtnDownload", resourceCulture) ?? "Download";
        public static string Single_BtnSaveAndDownload => ResourceManager.GetString("Single_BtnSaveAndDownload", resourceCulture) ?? "Save and download";
        public static string Single_GroupNavigator => ResourceManager.GetString("Single_GroupNavigator", resourceCulture) ?? "5. Navigation";
        public static string Single_NavAndDownload => ResourceManager.GetString("Single_NavAndDownload", resourceCulture) ?? "Navigate and download:";
        public static string Single_NavUp => ResourceManager.GetString("Single_NavUp", resourceCulture) ?? "Up";
        public static string Single_NavDown => ResourceManager.GetString("Single_NavDown", resourceCulture) ?? "Down";
        public static string Single_NavLeft => ResourceManager.GetString("Single_NavLeft", resourceCulture) ?? "Left";
        public static string Single_NavRight => ResourceManager.GetString("Single_NavRight", resourceCulture) ?? "Right";
        public static string Single_GroupKuidList => ResourceManager.GetString("Single_GroupKuidList", resourceCulture) ?? "Trainz basemap list:";
        public static string Single_GroupPreview => ResourceManager.GetString("Single_GroupPreview", resourceCulture) ?? "Downloaded basemap preview:";
        public static string Single_Status_Refreshing => ResourceManager.GetString("Single_Status_Refreshing", resourceCulture) ?? "Refreshing basemap list...";
        public static string Single_Status_Refreshed => ResourceManager.GetString("Single_Status_Refreshed", resourceCulture) ?? "Basemap list refreshed.";
        public static string Single_Status_Downloading => ResourceManager.GetString("Single_Status_Downloading", resourceCulture) ?? "Downloading map...";
        public static string Single_Status_FilesSaved => ResourceManager.GetString("Single_Status_FilesSaved", resourceCulture) ?? "Saved basemap: {0}";
        public static string Single_Status_DownloadedOnly => ResourceManager.GetString("Single_Status_DownloadedOnly", resourceCulture) ?? "Map downloaded to preview.";
        public static string Single_Status_AlreadyExists => ResourceManager.GetString("Single_Status_AlreadyExists", resourceCulture) ?? "Basemap already exists – skipped.";
        public static string Single_Status_Converted => ResourceManager.GetString("Single_Status_Converted", resourceCulture) ?? "Converted: {0}, {1} to {2}: {3}, {4}";
        public static string Single_Status_ConvertError => ResourceManager.GetString("Single_Status_ConvertError", resourceCulture) ?? "Coordinate conversion error: {0}, {1}";
        public static string Single_Status_FindingKuid => ResourceManager.GetString("Single_Status_FindingKuid", resourceCulture) ?? "Finding free KUID...";
        public static string Single_Status_FoundKuid => ResourceManager.GetString("Single_Status_FoundKuid", resourceCulture) ?? "Found free KUID: <kuid:{0}:{1}>";
        public static string Single_Status_FindingBasemapNum => ResourceManager.GetString("Single_Status_FindingBasemapNum", resourceCulture) ?? "Finding lowest free basemap number...";
        public static string Single_Status_FoundBasemapNum => ResourceManager.GetString("Single_Status_FoundBasemapNum", resourceCulture) ?? "Found lowest free basemap number: {0}";
        public static string Single_Err_RefreshList => ResourceManager.GetString("Single_Err_RefreshList", resourceCulture) ?? "Error refreshing basemap list:\n\n{0}";
        public static string Single_Err_AutoKuid => ResourceManager.GetString("Single_Err_AutoKuid", resourceCulture) ?? "Error automatically calculating KUID (part 2):\n\n{0}";
        public static string Single_Err_AutoBasemapNum => ResourceManager.GetString("Single_Err_AutoBasemapNum", resourceCulture) ?? "Error automatically calculating basemap number:\n\n{0}";
        public static string Single_Err_SavingFiles => ResourceManager.GetString("Single_Err_SavingFiles", resourceCulture) ?? "Error saving files:\n\n{0}";
        public static string Single_Err_Download => ResourceManager.GetString("Single_Err_Download", resourceCulture) ?? "Error downloading map:\n\n{0}";
        public static string Single_Err_FormatData => ResourceManager.GetString("Single_Err_FormatData", resourceCulture) ?? "Invalid start data (configuration error). Ensure you are using only digits and optional dot.\n\n{0}";
        public static string Single_Err_FormatTitle => ResourceManager.GetString("Single_Err_FormatTitle", resourceCulture) ?? "Format error";
        public static string Single_Err_BasemapName => ResourceManager.GetString("Single_Err_BasemapName", resourceCulture) ?? "Basemap name error.";
        public static string Single_Err_BasemapNameDetails => ResourceManager.GetString("Single_Err_BasemapNameDetails", resourceCulture) ?? "Basemap name error:\n\n{0}";

        public static string Unified_GroupCoords => ResourceManager.GetString("Unified_GroupCoords", resourceCulture) ?? "1. Coordinate system";
        public static string Unified_GroupSelection => ResourceManager.GetString("Unified_GroupSelection", resourceCulture) ?? "2. Area selection";
        public static string Unified_AreaFormat => ResourceManager.GetString("Unified_AreaFormat", resourceCulture) ?? "Area: {0:F2} km²";
        public static string Unified_BaseboardsFormat => ResourceManager.GetString("Unified_BaseboardsFormat", resourceCulture) ?? "Selected baseboards: {0}";
        public static string Unified_ResetBasePoint => ResourceManager.GetString("Unified_ResetBasePoint", resourceCulture) ?? "Reset base point";
        public static string Unified_ClearSelection => ResourceManager.GetString("Unified_ClearSelection", resourceCulture) ?? "Clear selection";
        public static string Unified_ModeBox => ResourceManager.GetString("Unified_ModeBox", resourceCulture) ?? "Box selection";
        public static string Unified_ModeClick => ResourceManager.GetString("Unified_ModeClick", resourceCulture) ?? "Brush / click";
        public static string Unified_GroupMap => ResourceManager.GetString("Unified_GroupMap", resourceCulture) ?? "Tile selection on map (local grid):";
        public static string Unified_GroupBasemapParams => ResourceManager.GetString("Unified_GroupBasemapParams", resourceCulture) ?? "3. Basemap parameters";
        public static string Unified_MaxResolution => ResourceManager.GetString("Unified_MaxResolution", resourceCulture) ?? "Max resolution:";
        public static string Unified_BasemapTypes => ResourceManager.GetString("Unified_BasemapTypes", resourceCulture) ?? "Basemap types (each creates a separate layer in Trainz):";
        public static string Unified_YearIfAvailable => ResourceManager.GetString("Unified_YearIfAvailable", resourceCulture) ?? "Year (if available):";
        public static string Unified_GroupConfigurator => ResourceManager.GetString("Unified_GroupConfigurator", resourceCulture) ?? "4. Configuration";
        public static string Unified_GeneratedRoutes => ResourceManager.GetString("Unified_GeneratedRoutes", resourceCulture) ?? "Generated routes:";
        public static string Unified_BtnLoadRoute => ResourceManager.GetString("Unified_BtnLoadRoute", resourceCulture) ?? "Load";
        public static string Unified_BtnDeleteRoute => ResourceManager.GetString("Unified_BtnDeleteRoute", resourceCulture) ?? "Delete";
        public static string Unified_RouteName => ResourceManager.GetString("Unified_RouteName", resourceCulture) ?? "Route name:";
        public static string Unified_BasemapDesignation => ResourceManager.GetString("Unified_BasemapDesignation", resourceCulture) ?? "Basemap name:";
        public static string Unified_BasemapNum => ResourceManager.GetString("Unified_BasemapNum", resourceCulture) ?? "Basemap #:";
        public static string Unified_KuidPart1 => ResourceManager.GetString("Unified_KuidPart1", resourceCulture) ?? "KUID designation:";
        public static string Unified_GroupDownload => ResourceManager.GetString("Unified_GroupDownload", resourceCulture) ?? "5. Download and generate map";
        public static string Unified_Gen2DBasemaps => ResourceManager.GetString("Unified_Gen2DBasemaps", resourceCulture) ?? "Generate 2D basemaps";
        public static string Unified_Place2DOnMap => ResourceManager.GetString("Unified_Place2DOnMap", resourceCulture) ?? "Place 2D basemaps on route";
        public static string Unified_Gen3DBasemaps => ResourceManager.GetString("Unified_Gen3DBasemaps", resourceCulture) ?? "Generate 3D basemaps";
        public static string Unified_Place3DOnMap => ResourceManager.GetString("Unified_Place3DOnMap", resourceCulture) ?? "Place 3D basemaps on route";
        public static string Unified_Gen3DTerrain => ResourceManager.GetString("Unified_Gen3DTerrain", resourceCulture) ?? "Generate 3D terrain";
        public static string Unified_GroupElevation => ResourceManager.GetString("Unified_GroupElevation", resourceCulture) ?? "Elevation mode:";
        public static string Unified_ElevationAbsolute => ResourceManager.GetString("Unified_ElevationAbsolute", resourceCulture) ?? "Actual AMSL (absolute)";
        public static string Unified_ElevationRelative => ResourceManager.GetString("Unified_ElevationRelative", resourceCulture) ?? "Zero-aligned (relative)";
        public static string Unified_ReadyToDownload => ResourceManager.GetString("Unified_ReadyToDownload", resourceCulture) ?? "Ready to download.";
        public static string Unified_BtnDownload => ResourceManager.GetString("Unified_BtnDownload", resourceCulture) ?? "Download";
        public static string Unified_BtnCancel => ResourceManager.GetString("Unified_BtnCancel", resourceCulture) ?? "Cancel";
        public static string Unified_NoTilesSelected => ResourceManager.GetString("Unified_NoTilesSelected", resourceCulture) ?? "No tiles selected on the map!";
        public static string Unified_NoSelectionTitle => ResourceManager.GetString("Unified_NoSelectionTitle", resourceCulture) ?? "No selection";
        public static string Unified_EnterRouteName => ResourceManager.GetString("Unified_EnterRouteName", resourceCulture) ?? "Enter the route name!";
        public static string Unified_SelectAtLeastOneGenOption => ResourceManager.GetString("Unified_SelectAtLeastOneGenOption", resourceCulture) ?? "Select at least one option in section '5. Download and generate map'!";
        public static string Unified_EnterBasemapDesignation => ResourceManager.GetString("Unified_EnterBasemapDesignation", resourceCulture) ?? "Enter the basemap designation!";
        public static string Unified_InvalidStartBasemapNum => ResourceManager.GetString("Unified_InvalidStartBasemapNum", resourceCulture) ?? "Invalid start basemap number!";
        public static string Unified_InvalidKuidPart2 => ResourceManager.GetString("Unified_InvalidKuidPart2", resourceCulture) ?? "Invalid KUID number (part 2)!";
        public static string Unified_SelectAtLeastOneBasemapType => ResourceManager.GetString("Unified_SelectAtLeastOneBasemapType", resourceCulture) ?? "Select at least one basemap type from the list!";
        public static string Unified_NoBasemapTypeTitle => ResourceManager.GetString("Unified_NoBasemapTypeTitle", resourceCulture) ?? "No basemap selected";
        public static string Unified_ConfirmRouteOverwrite => ResourceManager.GetString("Unified_ConfirmRouteOverwrite", resourceCulture) ?? "Route \"{0}\" already exists.\n\nContinuing will overwrite existing files.\nAre you sure you want to proceed?";
        public static string Unified_ConfirmRouteOverwriteTitle => ResourceManager.GetString("Unified_ConfirmRouteOverwriteTitle", resourceCulture) ?? "Route already exists";
        public static string Unified_TmiNotFoundFor3D => ResourceManager.GetString("Unified_TmiNotFoundFor3D", resourceCulture) ?? "3D basemap generation was selected, but TrainzMeshImporter.exe path is not configured or does not exist.\n\nOnly 2D basemaps will be generated.\nDo you want to continue?";
        public static string Unified_TmiMissingTitle => ResourceManager.GetString("Unified_TmiMissingTitle", resourceCulture) ?? "Missing TrainzMeshImporter";
        public static string Unified_SelectRouteToLoad => ResourceManager.GetString("Unified_SelectRouteToLoad", resourceCulture) ?? "Select a route from the list to load.";
        public static string Unified_MapStillInitializing => ResourceManager.GetString("Unified_MapStillInitializing", resourceCulture) ?? "The map component is still initializing. Please try again in a moment.";
        public static string Unified_MapfileNotFound => ResourceManager.GetString("Unified_MapfileNotFound", resourceCulture) ?? "mapfile.gnd was not found in the route folder:\n{0}";
        public static string Unified_RouteNoGeodata => ResourceManager.GetString("Unified_RouteNoGeodata", resourceCulture) ?? "Route \"{0}\" does not contain geolocation data (generated with an earlier version). It cannot be displayed on the map.";
        public static string Unified_RouteLoadError => ResourceManager.GetString("Unified_RouteLoadError", resourceCulture) ?? "Error while loading route:\n\n{0}";
        public static string Unified_SelectRouteToDelete => ResourceManager.GetString("Unified_SelectRouteToDelete", resourceCulture) ?? "Select a route from the list to delete.";
        public static string Unified_ConfirmRouteDelete => ResourceManager.GetString("Unified_ConfirmRouteDelete", resourceCulture) ?? "Are you sure you want to completely delete the route \"{0}\" and all its files?\n\nThis operation cannot be undone.";
        public static string Unified_ConfirmRouteDeleteTitle => ResourceManager.GetString("Unified_ConfirmRouteDeleteTitle", resourceCulture) ?? "Confirm route deletion";
        public static string Unified_RouteDeleteError => ResourceManager.GetString("Unified_RouteDeleteError", resourceCulture) ?? "Error while deleting route:\n\n{0}";
        public static string Unified_CompletedSuccess => ResourceManager.GetString("Unified_CompletedSuccess", resourceCulture) ?? "Operation completed successfully!\n\nGenerated: {0}.";
        public static string Unified_OperationCancelled => ResourceManager.GetString("Unified_OperationCancelled", resourceCulture) ?? "Operation cancelled.";
        public static string Unified_OperationCancelledTitle => ResourceManager.GetString("Unified_OperationCancelledTitle", resourceCulture) ?? "Cancelled";
        public static string Unified_GenerationError => ResourceManager.GetString("Unified_GenerationError", resourceCulture) ?? "Error during generation:\n\n{0}";
        public static string Unified_MapInitError => ResourceManager.GetString("Unified_MapInitError", resourceCulture) ?? "Error initializing map component:\n\n{0}";
        public static string Unified_Status_Refreshing => ResourceManager.GetString("Unified_Status_Refreshing", resourceCulture) ?? "Refreshing folder list...";
        public static string Unified_Status_Refreshed => ResourceManager.GetString("Unified_Status_Refreshed", resourceCulture) ?? "Folder list refreshed.";
        public static string Unified_Status_FindingKuid => ResourceManager.GetString("Unified_Status_FindingKuid", resourceCulture) ?? "Finding free KUID...";
        public static string Unified_Status_FoundKuid => ResourceManager.GetString("Unified_Status_FoundKuid", resourceCulture) ?? "Found free KUID: <kuid:{0}:{1}>";
        public static string Unified_Status_FindingBasemapNum => ResourceManager.GetString("Unified_Status_FindingBasemapNum", resourceCulture) ?? "Finding lowest free basemap number...";
        public static string Unified_Status_FoundBasemapNum => ResourceManager.GetString("Unified_Status_FoundBasemapNum", resourceCulture) ?? "Found lowest free basemap number: {0}";
        public static string Unified_Status_Preparing => ResourceManager.GetString("Unified_Status_Preparing", resourceCulture) ?? "Preparing...";
        public static string Unified_Status_Cancelling => ResourceManager.GetString("Unified_Status_Cancelling", resourceCulture) ?? "Cancelling...";

        public static string MapSource_OrtoWMTS => ResourceManager.GetString("MapSource_OrtoWMTS", resourceCulture) ?? "Orthophotomap WMTS";
        public static string MapSource_OrtoWMS => ResourceManager.GetString("MapSource_OrtoWMS", resourceCulture) ?? "Orthophotomap WMS, year selection";
        public static string MapSource_OrtoHighResWMTS => ResourceManager.GetString("MapSource_OrtoHighResWMTS", resourceCulture) ?? "Orthophotomap high resolution WMTS";
        public static string MapSource_OrtoHighResWMS => ResourceManager.GetString("MapSource_OrtoHighResWMS", resourceCulture) ?? "Orthophotomap high resolution WMS, year selection";
        public static string MapSource_ShadedWMTS => ResourceManager.GetString("MapSource_ShadedWMTS", resourceCulture) ?? "Shaded relief WMTS";
        public static string MapSource_ShadedWMS => ResourceManager.GetString("MapSource_ShadedWMS", resourceCulture) ?? "Shaded relief WMS";
        public static string MapSource_TopoWMTS => ResourceManager.GetString("MapSource_TopoWMTS", resourceCulture) ?? "Topographic map WMTS";

        public static string GeoSearch_Placeholder => ResourceManager.GetString("GeoSearch_Placeholder", resourceCulture) ?? "Search location...";
        public static string GeoSearch_SearchTitle => ResourceManager.GetString("GeoSearch_SearchTitle", resourceCulture) ?? "Search location";
        public static string GeoSearch_ClearTitle => ResourceManager.GetString("GeoSearch_ClearTitle", resourceCulture) ?? "Clear";
        public static string Unified_BtnUpdateRoute => ResourceManager.GetString("Unified_BtnUpdateRoute", resourceCulture) ?? "Update route";
        public static string Unified_Status_Help => ResourceManager.GetString("Unified_Status_Help", resourceCulture) ?? "LMB: Click or drag brush to select | RMB: Pan map";
        public static string Unified_Status_SelectInitialPoint => ResourceManager.GetString("Unified_Status_SelectInitialPoint", resourceCulture) ?? "Select starting point on the map.";
        public static string Unified_NewBaseboardsFormat => ResourceManager.GetString("Unified_NewBaseboardsFormat", resourceCulture) ?? "New baseboards: {0} (total: {1})";
        public static string Unified_Baseboards720Format => ResourceManager.GetString("Unified_Baseboards720Format", resourceCulture) ?? "Selected baseboards (720m): {0}";
        public static string Unified_Status_SelectedNew => ResourceManager.GetString("Unified_Status_SelectedNew", resourceCulture) ?? "Selected {0} new baseboards.";
        public static string Unified_Status_LoadedAddMore => ResourceManager.GetString("Unified_Status_LoadedAddMore", resourceCulture) ?? "Loaded {0} baseboards. Click on the map to add new ones.";
        public static string Unified_Status_SelectArea => ResourceManager.GetString("Unified_Status_SelectArea", resourceCulture) ?? "Select route area on the map.";
        public static string Unified_Status_LoadedCount => ResourceManager.GetString("Unified_Status_LoadedCount", resourceCulture) ?? "Loaded {0} baseboards.";
        public static string Unified_Status_ReadyToSelect => ResourceManager.GetString("Unified_Status_ReadyToSelect", resourceCulture) ?? "Ready to select.";
        public static string Unified_Status_ResetReady => ResourceManager.GetString("Unified_Status_ResetReady", resourceCulture) ?? "Reset. Ready to select.";
        public static string Unified_RouteLoadedStatus => ResourceManager.GetString("Unified_RouteLoadedStatus", resourceCulture) ?? "Loaded route \"{0}\" ({1} baseboards). You can select additional tiles and click Update.";
        public static string Unified_RouteLoadedNoGeoStatus => ResourceManager.GetString("Unified_RouteLoadedNoGeoStatus", resourceCulture) ?? "Loaded route \"{0}\" ({1} baseboards) without geolocation.";
        public static string Unified_RouteLoadedTitle => ResourceManager.GetString("Unified_RouteLoadedTitle", resourceCulture) ?? "Route loaded";
        public static string Unified_RouteDeletedStatus => ResourceManager.GetString("Unified_RouteDeletedStatus", resourceCulture) ?? "Deleted route \"{0}\".";
        public static string Unified_PromptEpsg2180ForElevation => ResourceManager.GetString("Unified_PromptEpsg2180ForElevation", resourceCulture) ?? "Downloading DEM elevation from Geoportal requires EPSG:2180 (Poland area).\nDo you want to automatically switch coordinate system to EPSG:2180?";
        public static string Unified_OutOfPolandBounds => ResourceManager.GetString("Unified_OutOfPolandBounds", resourceCulture) ?? "Tile ({0}, {1}) at coordinates ({2}, {3}) is outside Poland!\nGeoportal DEM provides data only for Poland.";
        public static string Unified_OutOfAreaTitle => ResourceManager.GetString("Unified_OutOfAreaTitle", resourceCulture) ?? "Outside area";
        public static string Unified_OperationInProgressExitConfirm => ResourceManager.GetString("Unified_OperationInProgressExitConfirm", resourceCulture) ?? "An operation is currently in progress. Are you sure you want to close the window and cancel it?";
        public static string Unified_OperationInProgressTitle => ResourceManager.GetString("Unified_OperationInProgressTitle", resourceCulture) ?? "Operation in progress";
        public static string Unified_Summary_2DBasemaps => ResourceManager.GetString("Unified_Summary_2DBasemaps", resourceCulture) ?? "2D basemaps ({0})";
        public static string Unified_Summary_3DBasemaps => ResourceManager.GetString("Unified_Summary_3DBasemaps", resourceCulture) ?? "3D basemaps ({0})";
        public static string Unified_Summary_3DTerrain => ResourceManager.GetString("Unified_Summary_3DTerrain", resourceCulture) ?? "3D terrain (map.gnd)";
        public static string Unified_Summary_Placed2D => ResourceManager.GetString("Unified_Summary_Placed2D", resourceCulture) ?? "placed 2D on map";
        public static string Unified_Summary_Placed3D => ResourceManager.GetString("Unified_Summary_Placed3D", resourceCulture) ?? "placed 3D on map";
        public static string Unified_Summary_Layers => ResourceManager.GetString("Unified_Summary_Layers", resourceCulture) ?? "Trainz layers ({0})";
        public static string Unified_Status_AutoBasemapNum => ResourceManager.GetString("Unified_Status_AutoBasemapNum", resourceCulture) ?? "Automatically selected basemap number: {0}";
        public static string Unified_Status_AutoKuid => ResourceManager.GetString("Unified_Status_AutoKuid", resourceCulture) ?? "Automatically selected KUID (part 2): {0}";
        public static string Unified_Status_RoutesRefreshed => ResourceManager.GetString("Unified_Status_RoutesRefreshed", resourceCulture) ?? "Route list refreshed";
        public static string Unified_Starting => ResourceManager.GetString("Unified_Starting", resourceCulture) ?? "Starting...";
        public static string Unified_DownloadingElevation => ResourceManager.GetString("Unified_DownloadingElevation", resourceCulture) ?? "Downloading elevation data...";
        public static string Unified_ElevationProgress => ResourceManager.GetString("Unified_ElevationProgress", resourceCulture) ?? "Elevation: {0}/{1}";
        public static string Unified_ElevationDownloaded => ResourceManager.GetString("Unified_ElevationDownloaded", resourceCulture) ?? "Downloaded elevation ({0},{1}) [{2}/{3}]";
        public static string Unified_ElevationWarning => ResourceManager.GetString("Unified_ElevationWarning", resourceCulture) ?? "[Warning] Failed to download elevation for ({0},{1}): {2}. Using height 0m.";
        public static string Unified_Downloading2D => ResourceManager.GetString("Unified_Downloading2D", resourceCulture) ?? "Downloading 2D ({0})...";
        public static string Unified_2DProgress => ResourceManager.GetString("Unified_2DProgress", resourceCulture) ?? "2D [{0}]: {1}/{2}";
        public static string Unified_2DFinishedSource => ResourceManager.GetString("Unified_2DFinishedSource", resourceCulture) ?? "2D basemaps ({0}): created {1}, errors {2}.";
        public static string Unified_Downloading3D => ResourceManager.GetString("Unified_Downloading3D", resourceCulture) ?? "Downloading 3D ({0})...";
        public static string Unified_3DProgress => ResourceManager.GetString("Unified_3DProgress", resourceCulture) ?? "3D [{0}]: {1}/{2}";
        public static string Unified_3DFinishedSource => ResourceManager.GetString("Unified_3DFinishedSource", resourceCulture) ?? "3D basemaps ({0}): created {1}, errors {2}.";
        public static string Unified_GeneratingGnd => ResourceManager.GetString("Unified_GeneratingGnd", resourceCulture) ?? "Generating mapfile.gnd...";
        public static string Unified_CreatingTrainzStructure => ResourceManager.GetString("Unified_CreatingTrainzStructure", resourceCulture) ?? "Creating Trainz map structure...";
        public static string Unified_Layers2D => ResourceManager.GetString("Unified_Layers2D", resourceCulture) ?? "2D Basemaps";
        public static string Unified_Layers3D => ResourceManager.GetString("Unified_Layers3D", resourceCulture) ?? "3D Basemaps";
        public static string Unified_Done => ResourceManager.GetString("Unified_Done", resourceCulture) ?? "Done!";
        public static string Unified_CompletedStatus => ResourceManager.GetString("Unified_CompletedStatus", resourceCulture) ?? "Completed: {0}.";
        public static string Unified_CancelledByUser => ResourceManager.GetString("Unified_CancelledByUser", resourceCulture) ?? "Operation cancelled by user.";
        public static string Unified_CancelledDialog => ResourceManager.GetString("Unified_CancelledDialog", resourceCulture) ?? "Operation has been interrupted.";
        public static string Unified_ErrorOccurred => ResourceManager.GetString("Unified_ErrorOccurred", resourceCulture) ?? "An error occurred!";
        public static string Unified_FallbackResolutionFailed => ResourceManager.GetString("Unified_FallbackResolutionFailed", resourceCulture) ?? "Failed to download basemap for ({0},{1}) in any available resolution.";
    }
}
